/**
 * Build the final coursework delivery package: runnable project notes,
 * dependency/run instructions, test records, screenshots, report, and ZIP.
 */

import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, posix } from "node:path";
import { buildZipStore, contentHash } from "../documents/exportFormats.js";
import type {
  CourseworkEvidenceItem,
  CourseworkSession,
  DeliveryPackageManifest,
  ProjectScopePolicy,
  SpecExtractResult
} from "./courseworkTypes.js";

export const DELIVERY_ZIP_KIND = "coursework-delivery-zip";
export const DELIVERY_README_KIND = "coursework-readme";
export const DELIVERY_MANIFEST_KIND = "coursework-manifest";

export interface DeliveryPackageInput {
  session: CourseworkSession;
  /** Optional extra file bodies to include (path → content). */
  extraFiles?: Array<{ path: string; data: string | Buffer }>;
  /** Directory to write package artifacts (required for disk write). */
  outputDir?: string;
  now?: () => Date;
}

export interface DeliveryPackageResult {
  manifest: DeliveryPackageManifest;
  zipBytes: Buffer;
  files: Array<{ path: string; data: Buffer }>;
}

export function buildReadmeMarkdown(session: CourseworkSession): string {
  const spec = session.spec;
  const lines: string[] = [
    `# ${session.title}`,
    "",
    `> Coursework session \`${session.id}\`${session.runId ? ` · run \`${session.runId}\`` : ""}`,
    `> Status: **${session.status}**`,
    "",
    "## Goal",
    "",
    session.goal,
    "",
    "## How to run",
    "",
    session.delivery?.runInstructionsPath
      ? `See \`${session.delivery.runInstructionsPath}\`.`
      : defaultRunInstructions(session),
    "",
    "## Dependencies",
    "",
    defaultDependencyNotes(session),
    ""
  ];

  if (spec) {
    lines.push("## Scoring points coverage", "");
    for (const sp of spec.scoringPoints) {
      const map = session.scoringMap.find((m) => m.scoringPointId === sp.id);
      const targets =
        map?.targets.map((t) => `${t.kind}:${t.ref}`).join(", ") || "_unmapped_";
      lines.push(`- **${sp.title}** (${sp.id}): ${targets}`);
    }
    lines.push("");

    if (spec.prohibitions.length) {
      lines.push("## Prohibitions observed", "");
      for (const p of spec.prohibitions) lines.push(`- ${p.text}`);
      lines.push("");
    }
  }

  if (session.scopePolicy.mode === "minimal_modify") {
    lines.push("## Minimal modification policy", "");
    lines.push("### Retained features");
    for (const f of session.scopePolicy.retainedFeatures) lines.push(`- ${f}`);
    if (!session.scopePolicy.retainedFeatures.length) lines.push("- _(none listed)_");
    lines.push("", "### Allowed modification scope");
    for (const a of session.scopePolicy.allowedModificationScope) lines.push(`- ${a}`);
    lines.push("");
  }

  lines.push("## Evidence index", "");
  if (session.evidence.length === 0) {
    lines.push("_No evidence attached yet._", "");
  } else {
    for (const e of session.evidence) {
      const flag = e.isPlaceholder ? " **[PLACEHOLDER — invalid for scoring]**" : "";
      lines.push(`- [${e.kind}] ${e.title}${e.path ? ` (\`${e.path}\`)` : ""}${flag}`);
    }
    lines.push("");
  }

  lines.push("## Provenance", "");
  lines.push("- Delivery package generated by CourseworkService (Task 34).");
  lines.push("- Final completion requires **user acceptance** — not agent self-claim.");
  lines.push(`- User accepted: **${session.userAccepted ? "yes" : "no"}**`);
  lines.push("");
  lines.push(`_Generated ${session.updatedAt}_`, "");
  return lines.join("\n");
}

export function buildRunInstructions(session: CourseworkSession): string {
  return [
    `# Run instructions — ${session.title}`,
    "",
    "1. Install dependencies (see DEPENDENCIES.md).",
    "2. Start / build the project using the commands recorded in test evidence.",
    "3. Verify scoring-point features manually if checklist items remain.",
    "",
    session.verificationSummary
      ? `## Last verification summary\n\n${session.verificationSummary}\n`
      : "## Verification\n\nAttach structured verification evidence (exit codes) before final review.\n",
    ""
  ].join("\n");
}

export function buildDependenciesMarkdown(session: CourseworkSession): string {
  return [
    `# Dependencies — ${session.title}`,
    "",
    "List runtime and dev dependencies required to run the project.",
    "Prefer lockfiles committed with the source tree.",
    "",
    session.existingProjectNotes
      ? `## Project notes\n\n${session.existingProjectNotes}\n`
      : "",
    "## Checklist",
    "",
    "- [ ] Package manager lockfile present",
    "- [ ] Environment variables documented (no secrets in ZIP)",
    "- [ ] Platform notes (Windows / Node version) recorded",
    ""
  ].join("\n");
}

export function buildManifestJson(session: CourseworkSession, entries: string[]): string {
  return JSON.stringify(
    {
      sessionId: session.id,
      title: session.title,
      goal: session.goal,
      status: session.status,
      userAccepted: session.userAccepted,
      scoringMap: session.scoringMap,
      scopePolicy: session.scopePolicy,
      evidence: session.evidence.map((e) => ({
        id: e.id,
        kind: e.kind,
        title: e.title,
        path: e.path,
        isPlaceholder: e.isPlaceholder === true,
        relatedScoringPointIds: e.relatedScoringPointIds
      })),
      deliveryFormats: session.spec?.deliveryFormat.formats ?? [],
      entries,
      reviewConclusion: session.review?.conclusion,
      generatedAt: session.updatedAt
    },
    null,
    2
  );
}

export function buildScoringMapMarkdown(session: CourseworkSession): string {
  const lines = [`# Scoring map — ${session.title}`, ""];
  const points = session.spec?.scoringPoints ?? [];
  for (const sp of points) {
    const map = session.scoringMap.find((m) => m.scoringPointId === sp.id);
    lines.push(`## ${sp.title} (\`${sp.id}\`)`);
    lines.push("");
    lines.push(sp.description);
    if (sp.maxScore != null) lines.push("", `Max score: ${sp.maxScore}`);
    lines.push("", "### Targets", "");
    if (!map || map.targets.length === 0) {
      lines.push("_Unmapped_");
    } else {
      for (const t of map.targets) {
        lines.push(`- **${t.kind}**: \`${t.ref}\`${t.note ? ` — ${t.note}` : ""}`);
      }
    }
    lines.push("", `Covered: **${map?.covered ? "yes" : "no"}**`, "");
  }
  return lines.join("\n");
}

/**
 * Assemble in-memory delivery files + ZIP (store method).
 * Does not require user accept — packaging can be previewed — but
 * CourseworkService only marks completed after accept.
 */
export function buildDeliveryPackage(input: DeliveryPackageInput): DeliveryPackageResult {
  const now = input.now ?? (() => new Date());
  const session = input.session;
  const files: Array<{ path: string; data: Buffer }> = [];

  const readme = buildReadmeMarkdown(session);
  const run = buildRunInstructions(session);
  const deps = buildDependenciesMarkdown(session);
  const scoring = buildScoringMapMarkdown(session);

  files.push({ path: "README.md", data: Buffer.from(readme, "utf8") });
  files.push({ path: "RUN.md", data: Buffer.from(run, "utf8") });
  files.push({ path: "DEPENDENCIES.md", data: Buffer.from(deps, "utf8") });
  files.push({ path: "SCORING_MAP.md", data: Buffer.from(scoring, "utf8") });

  // Evidence catalog + copies of text evidence bodies
  const testRecords: string[] = [];
  const screenshots: string[] = [];
  const reportPaths: string[] = [];

  const catalogLines = ["# Evidence catalog", ""];
  for (const e of session.evidence) {
    catalogLines.push(`## ${e.title}`);
    catalogLines.push(`- id: ${e.id}`);
    catalogLines.push(`- kind: ${e.kind}`);
    if (e.path) catalogLines.push(`- path: ${e.path}`);
    catalogLines.push(`- placeholder: ${e.isPlaceholder === true}`);
    catalogLines.push(
      `- scoring: ${e.relatedScoringPointIds.join(", ") || "_none_"}`
    );
    catalogLines.push("");

    const dest =
      e.kind === "screenshot"
        ? `evidence/screenshots/${safeName(e.title)}.txt`
        : e.kind === "test_record" || e.kind === "verification"
          ? `evidence/tests/${safeName(e.title)}.md`
          : e.kind === "document"
            ? `evidence/reports/${safeName(e.title)}.md`
            : `evidence/other/${safeName(e.title)}.md`;

    const body = evidenceBody(e);
    files.push({ path: dest, data: Buffer.from(body, "utf8") });

    if (e.kind === "screenshot") screenshots.push(dest);
    if (e.kind === "test_record" || e.kind === "verification" || e.kind === "run_log") {
      testRecords.push(dest);
    }
    if (e.kind === "document") reportPaths.push(dest);
  }
  files.push({
    path: "evidence/CATALOG.md",
    data: Buffer.from(catalogLines.join("\n"), "utf8")
  });

  // Report stub if none
  if (reportPaths.length === 0) {
    const report = [
      `# Coursework report — ${session.title}`,
      "",
      session.goal,
      "",
      "Bind this report to DocumentService export when available.",
      ""
    ].join("\n");
    files.push({ path: "report/REPORT.md", data: Buffer.from(report, "utf8") });
    reportPaths.push("report/REPORT.md");
  }

  if (input.extraFiles) {
    for (const f of input.extraFiles) {
      const data = typeof f.data === "string" ? Buffer.from(f.data, "utf8") : f.data;
      files.push({ path: f.path.replace(/\\/g, "/"), data });
    }
  }

  const entryPaths = files.map((f) => f.path);
  const manifestJson = buildManifestJson(session, entryPaths);
  files.push({ path: "MANIFEST.json", data: Buffer.from(manifestJson, "utf8") });

  const zipBytes = buildZipStore(
    files.map((f) => ({ name: f.path, data: f.data }))
  );
  const zipHash = contentHash(zipBytes);

  const manifest: DeliveryPackageManifest = {
    projectRunnable: session.evidence.some(
      (e) =>
        !e.isPlaceholder &&
        (e.kind === "verification" || e.kind === "run_log" || e.kind === "test_record")
    ),
    readmePath: "README.md",
    runInstructionsPath: "RUN.md",
    dependencyNotesPath: "DEPENDENCIES.md",
    testRecords,
    screenshots,
    reportPaths,
    zipPath: "delivery.zip",
    zipContentHash: zipHash,
    entries: [...entryPaths, "delivery.zip"],
    createdAt: now().toISOString()
  };

  return { manifest, zipBytes, files };
}

export async function writeDeliveryPackage(
  input: DeliveryPackageInput
): Promise<DeliveryPackageResult> {
  const result = buildDeliveryPackage(input);
  if (!input.outputDir) return result;

  await mkdir(input.outputDir, { recursive: true });
  for (const f of result.files) {
    const abs = join(input.outputDir, ...f.path.split("/"));
    await mkdir(dirname(abs), { recursive: true });
    await writeFile(abs, f.data);
  }
  const zipAbs = join(input.outputDir, "delivery.zip");
  await writeFile(zipAbs, result.zipBytes);
  result.manifest.zipPath = zipAbs;
  return result;
}

function defaultRunInstructions(session: CourseworkSession): string {
  return [
    "1. Install dependencies for the project stack.",
    "2. Run the verified start/test commands from evidence.",
    `3. Confirm scoring features for: ${session.spec?.scoringPoints.map((s) => s.title).join(", ") || session.title}.`
  ].join("\n");
}

function defaultDependencyNotes(session: CourseworkSession): string {
  if (session.existingProjectNotes?.trim()) {
    return `See project notes and DEPENDENCIES.md.\n\n${session.existingProjectNotes.slice(0, 500)}`;
  }
  return "See DEPENDENCIES.md and the project lockfile.";
}

function evidenceBody(e: CourseworkEvidenceItem): string {
  const lines = [
    `# ${e.title}`,
    "",
    `- kind: ${e.kind}`,
    `- id: ${e.id}`,
    `- createdAt: ${e.createdAt}`,
    `- placeholder: ${e.isPlaceholder === true}`,
    ""
  ];
  if (e.path) lines.push(`Source path: \`${e.path}\``, "");
  if (e.verification) {
    lines.push("## Verification", "");
    lines.push(e.verification.summary);
    lines.push(`allPassed: ${e.verification.allPassed}`);
    for (const r of e.verification.results) {
      lines.push(
        `- \`${r.command.join(" ")}\` exit=${r.exitCode} passed=${r.passed}`
      );
    }
    lines.push("");
  }
  if (e.metadata && Object.keys(e.metadata).length) {
    lines.push("## Metadata", "", "```json", JSON.stringify(e.metadata, null, 2), "```", "");
  }
  return lines.join("\n");
}

function safeName(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9\u4e00-\u9fff]+/gi, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 48) || "item"
  );
}

export function packageContentHash(bytes: Buffer): string {
  return createHash("sha256").update(bytes).digest("hex").slice(0, 32);
}

/** Validate delivery completeness against extracted delivery formats. */
export function deliveryCompleteness(
  session: CourseworkSession,
  manifest: DeliveryPackageManifest
): { ok: boolean; missing: string[] } {
  const formats = session.spec?.deliveryFormat.formats ?? [];
  const missing: string[] = [];
  for (const f of formats) {
    switch (f) {
      case "zip":
        if (!manifest.zipPath) missing.push("zip");
        break;
      case "readme":
        if (!manifest.readmePath) missing.push("readme");
        break;
      case "screenshots":
        if (manifest.screenshots.length === 0) missing.push("screenshots");
        break;
      case "test-records":
        if (manifest.testRecords.length === 0) missing.push("test-records");
        break;
      case "report":
      case "report-pdf":
        if (manifest.reportPaths.length === 0) missing.push("report");
        break;
      case "runnable-project":
        if (!manifest.projectRunnable) missing.push("runnable-project");
        break;
      case "source":
        // Source is the project workspace; package includes notes only.
        break;
      default:
        break;
    }
  }
  // Always require readme + zip for coursework pack
  if (!manifest.readmePath) missing.push("readme");
  if (!manifest.zipPath) missing.push("zip");
  return { ok: missing.length === 0, missing: [...new Set(missing)] };
}

export function describeScope(policy: ProjectScopePolicy): string {
  return [
    `mode=${policy.mode}`,
    `retained=${policy.retainedFeatures.length}`,
    `allowed=${policy.allowedModificationScope.join("|")}`
  ].join(" ");
}

// silence unused import in case tree-shakers complain about posix in some builds
void posix;
