/**
 * Full provider catalog aligned with todos-dev CLI / @earendil-works/pi-ai builtins.
 * Generated from pi-ai 0.80.7 getBuiltinProviders() + ollama/custom SPECIAL.
 * Secrets never live here — only non-sensitive metadata + env var *names*.
 */

import type { ProviderPresetChoice } from "./providerTypes.js";

export const PROVIDER_CLI_PRESETS: readonly ProviderPresetChoice[] = [
  {
    id: "amazon-bedrock",
    name: "Amazon Bedrock",
    label: "Amazon Bedrock",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
    apiProtocol: "bedrock-converse-stream",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Amazon Bedrock (109 built-in models)",
    credentialEnvVar: "AWS_BEARER_TOKEN_BEDROCK",
    defaultModelId: "amazon.nova-2-lite-v1:0",
  },
  {
    id: "ant-ling",
    name: "Ant Ling",
    label: "Ant Ling",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.ant-ling.com/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Ant Ling (3 built-in models)",
    credentialEnvVar: "ANT_LING_API_KEY",
    defaultModelId: "Ling-2.6-1T",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    label: "Anthropic",
    hint: "Built-in — OAuth (subscription) or API key",
    adapter: "anthropic",
    providerType: "builtin",
    defaultBaseUrl: "https://api.anthropic.com",
    apiProtocol: "anthropic-messages",
    authModes: ["oauth","api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Anthropic (14 built-in models)",
    credentialEnvVar: "ANTHROPIC_API_KEY",
    defaultModelId: "claude-fable-5",
  },
  {
    id: "azure-openai-responses",
    name: "Azure OpenAI (Responses)",
    label: "Azure OpenAI (Responses)",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    apiProtocol: "azure-openai-responses",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Azure OpenAI (Responses) (46 built-in models)",
    credentialEnvVar: "AZURE_OPENAI_API_KEY",
    defaultModelId: "gpt-4",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    label: "Cerebras",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.cerebras.ai/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Cerebras (3 built-in models)",
    credentialEnvVar: "CEREBRAS_API_KEY",
    defaultModelId: "gemma-4-31b",
  },
  {
    id: "cloudflare-ai-gateway",
    name: "Cloudflare AI Gateway",
    label: "Cloudflare AI Gateway",
    hint: "Built-in — just paste an API key",
    adapter: "anthropic",
    providerType: "builtin",
    defaultBaseUrl: "https://gateway.ai.cloudflare.com/v1/{CLOUDFLARE_ACCOUNT_ID}/{CLOUDFLARE_GATEWAY_ID}/anthropic",
    apiProtocol: "anthropic-messages",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Cloudflare AI Gateway (42 built-in models)",
    credentialEnvVar: "CLOUDFLARE_API_KEY",
    defaultModelId: "claude-3-5-haiku",
  },
  {
    id: "cloudflare-workers-ai",
    name: "Cloudflare Workers AI",
    label: "Cloudflare Workers AI",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Cloudflare Workers AI (13 built-in models)",
    credentialEnvVar: "CLOUDFLARE_API_KEY",
    defaultModelId: "@cf/google/gemma-4-26b-a4b-it",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    label: "DeepSeek",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.deepseek.com",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "DeepSeek (2 built-in models)",
    credentialEnvVar: "DEEPSEEK_API_KEY",
    defaultModelId: "deepseek-v4-flash",
  },
  {
    id: "fireworks",
    name: "Fireworks",
    label: "Fireworks",
    hint: "Built-in — just paste an API key",
    adapter: "anthropic",
    providerType: "builtin",
    defaultBaseUrl: "https://api.fireworks.ai/inference",
    apiProtocol: "anthropic-messages",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Fireworks (16 built-in models)",
    credentialEnvVar: "FIREWORKS_API_KEY",
    defaultModelId: "accounts/fireworks/models/deepseek-v4-flash",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    label: "GitHub Copilot",
    hint: "Built-in — OAuth (subscription)",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.individual.githubcopilot.com",
    apiProtocol: "openai-completions",
    authModes: ["oauth"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "GitHub Copilot (28 built-in models)",
    credentialEnvVar: "COPILOT_GITHUB_TOKEN",
    defaultModelId: "claude-fable-5",
  },
  {
    id: "google",
    name: "Google Gemini",
    label: "Google Gemini",
    hint: "Built-in — just paste an API key",
    adapter: "gemini",
    providerType: "builtin",
    defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
    apiProtocol: "google-generative-ai",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Google Gemini (16 built-in models)",
    credentialEnvVar: "GEMINI_API_KEY",
    defaultModelId: "gemini-2.0-flash",
  },
  {
    id: "google-vertex",
    name: "Google Vertex AI",
    label: "Google Vertex AI",
    hint: "Built-in — just paste an API key",
    adapter: "gemini",
    providerType: "builtin",
    defaultBaseUrl: "https://{location}-aiplatform.googleapis.com",
    apiProtocol: "google-vertex",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Google Vertex AI (10 built-in models)",
    credentialEnvVar: "GOOGLE_CLOUD_API_KEY",
    defaultModelId: "gemini-2.5-flash",
  },
  {
    id: "groq",
    name: "Groq",
    label: "Groq",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Groq (7 built-in models)",
    credentialEnvVar: "GROQ_API_KEY",
    defaultModelId: "llama-3.1-8b-instant",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    label: "Hugging Face",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://router.huggingface.co/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Hugging Face (49 built-in models)",
    credentialEnvVar: "HF_TOKEN",
    defaultModelId: "MiniMaxAI/MiniMax-M2",
  },
  {
    id: "kimi-coding",
    name: "Kimi For Coding",
    label: "Kimi For Coding",
    hint: "Built-in — just paste an API key",
    adapter: "anthropic",
    providerType: "builtin",
    defaultBaseUrl: "https://api.kimi.com/coding",
    apiProtocol: "anthropic-messages",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Kimi For Coding (3 built-in models)",
    credentialEnvVar: "KIMI_API_KEY",
    defaultModelId: "k2p7",
  },
  {
    id: "minimax",
    name: "MiniMax",
    label: "MiniMax",
    hint: "Built-in — just paste an API key",
    adapter: "anthropic",
    providerType: "builtin",
    defaultBaseUrl: "https://api.minimax.io/anthropic",
    apiProtocol: "anthropic-messages",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "MiniMax (3 built-in models)",
    credentialEnvVar: "MINIMAX_API_KEY",
    defaultModelId: "MiniMax-M2.7",
  },
  {
    id: "minimax-cn",
    name: "MiniMax (China)",
    label: "MiniMax (China)",
    hint: "Built-in — just paste an API key",
    adapter: "anthropic",
    providerType: "builtin",
    defaultBaseUrl: "https://api.minimaxi.com/anthropic",
    apiProtocol: "anthropic-messages",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "MiniMax (China) (3 built-in models)",
    credentialEnvVar: "MINIMAX_CN_API_KEY",
    defaultModelId: "MiniMax-M2.7",
  },
  {
    id: "mistral",
    name: "Mistral",
    label: "Mistral",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.mistral.ai",
    apiProtocol: "mistral-conversations",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Mistral (30 built-in models)",
    credentialEnvVar: "MISTRAL_API_KEY",
    defaultModelId: "codestral-latest",
  },
  {
    id: "moonshotai",
    name: "Moonshot AI",
    label: "Moonshot AI",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.moonshot.ai/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Moonshot AI (9 built-in models)",
    credentialEnvVar: "MOONSHOT_API_KEY",
    defaultModelId: "kimi-k2-0711-preview",
  },
  {
    id: "moonshotai-cn",
    name: "Moonshot AI (China)",
    label: "Moonshot AI (China)",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.moonshot.cn/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Moonshot AI (China) (9 built-in models)",
    credentialEnvVar: "MOONSHOT_API_KEY",
    defaultModelId: "kimi-k2-0711-preview",
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    label: "NVIDIA NIM",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://integrate.api.nvidia.com/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "NVIDIA NIM (20 built-in models)",
    credentialEnvVar: "NVIDIA_API_KEY",
    defaultModelId: "meta/llama-3.1-70b-instruct",
  },
  {
    id: "openai",
    name: "OpenAI",
    label: "OpenAI",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.openai.com/v1",
    apiProtocol: "openai-responses",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "OpenAI (46 built-in models)",
    credentialEnvVar: "OPENAI_API_KEY",
    defaultModelId: "gpt-4",
  },
  {
    id: "openai-codex",
    name: "OpenAI Codex (ChatGPT Plus/Pro)",
    label: "OpenAI Codex (ChatGPT Plus/Pro)",
    hint: "Built-in — OAuth (subscription)",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://chatgpt.com/backend-api",
    apiProtocol: "openai-codex-responses",
    authModes: ["oauth"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "OpenAI Codex (ChatGPT Plus/Pro) (7 built-in models)",
    credentialEnvVar: "OPENAI_API_KEY",
    defaultModelId: "gpt-5.3-codex-spark",
  },
  {
    id: "opencode",
    name: "OpenCode Zen",
    label: "OpenCode Zen",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://opencode.ai/zen/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "OpenCode Zen (54 built-in models)",
    credentialEnvVar: "OPENCODE_API_KEY",
    defaultModelId: "big-pickle",
  },
  {
    id: "opencode-go",
    name: "OpenCode Go",
    label: "OpenCode Go",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://opencode.ai/zen/go/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "OpenCode Go (13 built-in models)",
    credentialEnvVar: "OPENCODE_API_KEY",
    defaultModelId: "deepseek-v4-flash",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    label: "OpenRouter",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "OpenRouter (269 built-in models)",
    credentialEnvVar: "OPENROUTER_API_KEY",
    defaultModelId: "ai21/jamba-large-1.7",
  },
  {
    id: "together",
    name: "Together AI",
    label: "Together AI",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.together.ai/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Together AI (20 built-in models)",
    credentialEnvVar: "TOGETHER_API_KEY",
    defaultModelId: "MiniMaxAI/MiniMax-M2.7",
  },
  {
    id: "vercel-ai-gateway",
    name: "Vercel AI Gateway",
    label: "Vercel AI Gateway",
    hint: "Built-in — just paste an API key",
    adapter: "anthropic",
    providerType: "builtin",
    defaultBaseUrl: "https://ai-gateway.vercel.sh",
    apiProtocol: "anthropic-messages",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Vercel AI Gateway (186 built-in models)",
    credentialEnvVar: "AI_GATEWAY_API_KEY",
    defaultModelId: "alibaba/qwen-3-14b",
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    label: "xAI (Grok)",
    hint: "Built-in — OAuth (subscription) or API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.x.ai/v1",
    apiProtocol: "openai-completions",
    authModes: ["oauth","api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "xAI (Grok) (8 built-in models)",
    credentialEnvVar: "XAI_API_KEY",
    defaultModelId: "grok-3",
  },
  {
    id: "xiaomi",
    name: "Xiaomi MiMo",
    label: "Xiaomi MiMo",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.xiaomimimo.com/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Xiaomi MiMo (6 built-in models)",
    credentialEnvVar: "XIAOMI_API_KEY",
    defaultModelId: "mimo-v2-flash",
  },
  {
    id: "xiaomi-token-plan-ams",
    name: "Xiaomi MiMo Token Plan (Amsterdam)",
    label: "Xiaomi MiMo Token Plan (Amsterdam)",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://token-plan-ams.xiaomimimo.com/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Xiaomi MiMo Token Plan (Amsterdam) (3 built-in models)",
    credentialEnvVar: "XIAOMI_TOKEN_PLAN_AMS_API_KEY",
    defaultModelId: "mimo-v2-pro",
  },
  {
    id: "xiaomi-token-plan-cn",
    name: "Xiaomi MiMo Token Plan (China)",
    label: "Xiaomi MiMo Token Plan (China)",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Xiaomi MiMo Token Plan (China) (3 built-in models)",
    credentialEnvVar: "XIAOMI_TOKEN_PLAN_CN_API_KEY",
    defaultModelId: "mimo-v2-pro",
  },
  {
    id: "xiaomi-token-plan-sgp",
    name: "Xiaomi MiMo Token Plan (Singapore)",
    label: "Xiaomi MiMo Token Plan (Singapore)",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://token-plan-sgp.xiaomimimo.com/v1",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "Xiaomi MiMo Token Plan (Singapore) (3 built-in models)",
    credentialEnvVar: "XIAOMI_TOKEN_PLAN_SGP_API_KEY",
    defaultModelId: "mimo-v2-pro",
  },
  {
    id: "zai",
    name: "ZAI Coding Plan (Global)",
    label: "ZAI Coding Plan (Global)",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://api.z.ai/api/coding/paas/v4",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "ZAI Coding Plan (Global) (6 built-in models)",
    credentialEnvVar: "ZAI_API_KEY",
    defaultModelId: "glm-4.5-air",
  },
  {
    id: "zai-coding-cn",
    name: "ZAI Coding Plan (China)",
    label: "ZAI Coding Plan (China)",
    hint: "Built-in — just paste an API key",
    adapter: "openai-compatible",
    providerType: "builtin",
    defaultBaseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: false,
    description: "ZAI Coding Plan (China) (6 built-in models)",
    credentialEnvVar: "ZAI_CODING_CN_API_KEY",
    defaultModelId: "glm-4.5-air",
  },
  {
    id: "ollama",
    name: "Ollama",
    label: "Ollama (local)",
    hint: "Local LLMs via Ollama — no API key required",
    adapter: "ollama",
    providerType: "local",
    defaultBaseUrl: "http://localhost:11434/v1",
    apiProtocol: "openai-completions",
    authModes: ["none"],
    requiresCredential: false,
    allowDeferredCredential: true,
    description: "Local Ollama OpenAI-compatible endpoint",
  },
  {
    id: "custom",
    name: "Custom",
    label: "Custom (manual setup)",
    hint: "Configure baseUrl / api / model list yourself",
    adapter: "openai-compatible",
    providerType: "custom",
    apiProtocol: "openai-completions",
    authModes: ["api-key"],
    requiresCredential: true,
    allowDeferredCredential: true,
    description: "Any OpenAI-compatible gateway or relay",
  },
];

export function listProviderCliPresets(): ProviderPresetChoice[] {
  return PROVIDER_CLI_PRESETS.map((p) => ({ ...p }));
}
